name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile --console main_wechat_info.py

    - name: Compress EXE into zip
      run: |
        mkdir output
        copy dist\main_wechat_info.exe output\
        powershell Compress-Archive -Path output\* -DestinationPath wechat_info.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: wechat_info_build
        path: wechat_info.zip
